#!/usr/bin/env python

#-----------------------------------------------------------------------
# keys.py
# Author: Owen Travis
#-----------------------------------------------------------------------

# Generated by os.urandom(16)
APP_SECRET_KEY = b'\xb1\x80{(\xa4l\x8a\xacW,@<4\x18\x84\x8a'
